### ISSUE TITLE
How to train using my own captured data

### ISSUE THREAD

**Issue by Aulianfie** [Riga2/TensoSDF#8]
您好！

我正在尝试使用 TensoSDF 进行训练，但我不确定如何使用现实中拍摄的数据。我按照NeRO文档中的说明准备了一些数据，但在训练时遇到了一些问题。以下是我的具体步骤和问题：

我使用了NeRO中提供的方法和他们提供的 kettle 数据，运行 run_colmap.py 生成了如下的文件夹

![Image](https://github.com/user-attachments/assets/ef534de9-ddd8-4dde-9495-a62545a1a25e)

并且修改了yaml文件
``` yaml
name: kettle_shape

####network#####
network: shape
database_name: real/kettle/raw_1024 # changed
split_manul: true
nerfDataType: True


####dataset#####
train_dataset_type: dummy
dataset_dir: /home/wdh/TensoSDF/Datasets/kettle           # !!!! change your dataset dir !!!!
train_dataset_cfg:
  database_name: real/kettle/raw_1024 # changed
  split_manul: true
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: real/kettle/raw_1024 # changed
      split_manul: true

```
但是我的运行run_train.py 进行Geometry reconstruction后，没有生成shape的点云文件和albedo，normals，roughness等图像

![Image](https://github.com/user-attachments/assets/a1489da5-e2e1-4b30-a6d3-328c94684f0b)

我的问题

* 我的数据准备步骤是否正确？是否有遗漏？
* 配置文件需要如何调整以适应我的数据？
* 是否有示例或文档可以参考，以便更好地理解如何使用自定义数据？

非常感谢您的帮助！
